# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Jun  6 12:33:53 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 960)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 100))
        self.tabWidget.setObjectName("tabWidget")
        self.PreviewTab = QtWidgets.QWidget()
        self.PreviewTab.setObjectName("PreviewTab")
        self.gridLayout = QtWidgets.QGridLayout(self.PreviewTab)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.PreviewTab)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 2, 1, 1)
        self.OptionsGroupBox = QtWidgets.QGroupBox(self.PreviewTab)
        self.OptionsGroupBox.setMinimumSize(QtCore.QSize(150, 200))
        self.OptionsGroupBox.setObjectName("OptionsGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.OptionsGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startSimulationButton = QtWidgets.QPushButton(self.OptionsGroupBox)
        self.startSimulationButton.setObjectName("startSimulationButton")
        self.verticalLayout.addWidget(self.startSimulationButton)
        self.stopSimulationButton = QtWidgets.QPushButton(self.OptionsGroupBox)
        self.stopSimulationButton.setObjectName("stopSimulationButton")
        self.verticalLayout.addWidget(self.stopSimulationButton)
        self.saveStateButton = QtWidgets.QPushButton(self.OptionsGroupBox)
        self.saveStateButton.setObjectName("saveStateButton")
        self.verticalLayout.addWidget(self.saveStateButton)
        self.loadStateButton = QtWidgets.QPushButton(self.OptionsGroupBox)
        self.loadStateButton.setObjectName("loadStateButton")
        self.verticalLayout.addWidget(self.loadStateButton)
        self.line_2 = QtWidgets.QFrame(self.OptionsGroupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_4 = QtWidgets.QLabel(self.OptionsGroupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.framerateBox = QtWidgets.QDoubleSpinBox(self.OptionsGroupBox)
        self.framerateBox.setMaximum(1000000.0)
        self.framerateBox.setProperty("value", 10.0)
        self.framerateBox.setObjectName("framerateBox")
        self.verticalLayout.addWidget(self.framerateBox)
        self.label = QtWidgets.QLabel(self.OptionsGroupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frameSkipping = QtWidgets.QSpinBox(self.OptionsGroupBox)
        self.frameSkipping.setMaximum(1000000)
        self.frameSkipping.setObjectName("frameSkipping")
        self.verticalLayout.addWidget(self.frameSkipping)
        self.multithreaded = QtWidgets.QCheckBox(self.OptionsGroupBox)
        self.multithreaded.setObjectName("multithreaded")
        self.verticalLayout.addWidget(self.multithreaded)
        self.line = QtWidgets.QFrame(self.OptionsGroupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(self.OptionsGroupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.drawFoods = QtWidgets.QRadioButton(self.OptionsGroupBox)
        self.drawFoods.setChecked(True)
        self.drawFoods.setObjectName("drawFoods")
        self.painterButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.painterButtonGroup.setObjectName("painterButtonGroup")
        self.painterButtonGroup.addButton(self.drawFoods)
        self.verticalLayout.addWidget(self.drawFoods)
        self.drawObstacles = QtWidgets.QRadioButton(self.OptionsGroupBox)
        self.drawObstacles.setObjectName("drawObstacles")
        self.painterButtonGroup.addButton(self.drawObstacles)
        self.verticalLayout.addWidget(self.drawObstacles)
        self.drawPheromoneToFood = QtWidgets.QRadioButton(self.OptionsGroupBox)
        self.drawPheromoneToFood.setObjectName("drawPheromoneToFood")
        self.painterButtonGroup.addButton(self.drawPheromoneToFood)
        self.verticalLayout.addWidget(self.drawPheromoneToFood)
        self.drawPheromoneFromFood = QtWidgets.QRadioButton(self.OptionsGroupBox)
        self.drawPheromoneFromFood.setObjectName("drawPheromoneFromFood")
        self.painterButtonGroup.addButton(self.drawPheromoneFromFood)
        self.verticalLayout.addWidget(self.drawPheromoneFromFood)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.painterRadius = QtWidgets.QDial(self.OptionsGroupBox)
        self.painterRadius.setMaximumSize(QtCore.QSize(50, 50))
        self.painterRadius.setMinimum(3)
        self.painterRadius.setMaximum(25)
        self.painterRadius.setProperty("value", 5)
        self.painterRadius.setObjectName("painterRadius")
        self.gridLayout_2.addWidget(self.painterRadius, 1, 1, 1, 1)
        self.painterIntensity = QtWidgets.QDial(self.OptionsGroupBox)
        self.painterIntensity.setMaximumSize(QtCore.QSize(50, 50))
        self.painterIntensity.setProperty("value", 30)
        self.painterIntensity.setObjectName("painterIntensity")
        self.gridLayout_2.addWidget(self.painterIntensity, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.OptionsGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.OptionsGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_3 = QtWidgets.QFrame(self.OptionsGroupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_6 = QtWidgets.QLabel(self.OptionsGroupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.OptionsGroupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.displayPheromones1 = QtWidgets.QCheckBox(self.OptionsGroupBox)
        self.displayPheromones1.setChecked(True)
        self.displayPheromones1.setObjectName("displayPheromones1")
        self.horizontalLayout_2.addWidget(self.displayPheromones1)
        self.displayPheromones2 = QtWidgets.QCheckBox(self.OptionsGroupBox)
        self.displayPheromones2.setChecked(True)
        self.displayPheromones2.setObjectName("displayPheromones2")
        self.horizontalLayout_2.addWidget(self.displayPheromones2)
        self.displayPheromones3 = QtWidgets.QCheckBox(self.OptionsGroupBox)
        self.displayPheromones3.setChecked(True)
        self.displayPheromones3.setObjectName("displayPheromones3")
        self.horizontalLayout_2.addWidget(self.displayPheromones3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.displayRanges = QtWidgets.QCheckBox(self.OptionsGroupBox)
        self.displayRanges.setChecked(False)
        self.displayRanges.setObjectName("displayRanges")
        self.verticalLayout.addWidget(self.displayRanges)
        self.disableGraphics = QtWidgets.QCheckBox(self.OptionsGroupBox)
        self.disableGraphics.setChecked(False)
        self.disableGraphics.setObjectName("disableGraphics")
        self.verticalLayout.addWidget(self.disableGraphics)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.OptionsGroupBox, 0, 1, 1, 1)
        self.tabWidget.addTab(self.PreviewTab, "")
        self.StatsTab = QtWidgets.QWidget()
        self.StatsTab.setObjectName("StatsTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.StatsTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stats_label = QtWidgets.QLabel(self.StatsTab)
        self.stats_label.setObjectName("stats_label")
        self.gridLayout_3.addWidget(self.stats_label, 0, 0, 1, 1)
        self.tabWidget.addTab(self.StatsTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OptionsGroupBox.setTitle(_translate("MainWindow", "Options"))
        self.startSimulationButton.setText(_translate("MainWindow", "Start Simulation"))
        self.stopSimulationButton.setText(_translate("MainWindow", "Stop Simulation"))
        self.saveStateButton.setText(_translate("MainWindow", "Save state"))
        self.loadStateButton.setText(_translate("MainWindow", "Load state"))
        self.label_4.setText(_translate("MainWindow", "Framerate:"))
        self.label.setText(_translate("MainWindow", "Frame skipping"))
        self.multithreaded.setText(_translate("MainWindow", "Multithreaded"))
        self.label_3.setText(_translate("MainWindow", "Paint:"))
        self.drawFoods.setText(_translate("MainWindow", "Foods"))
        self.drawObstacles.setText(_translate("MainWindow", "Obstacles"))
        self.drawPheromoneToFood.setText(_translate("MainWindow", "Pheromone (to food)"))
        self.drawPheromoneFromFood.setText(_translate("MainWindow", "Pheromone (from food)"))
        self.label_2.setText(_translate("MainWindow", "Intensity"))
        self.label_5.setText(_translate("MainWindow", "Radius"))
        self.label_6.setText(_translate("MainWindow", "Display:"))
        self.label_7.setText(_translate("MainWindow", "Pheromones:"))
        self.displayPheromones1.setText(_translate("MainWindow", "1"))
        self.displayPheromones2.setText(_translate("MainWindow", "2"))
        self.displayPheromones3.setText(_translate("MainWindow", "3"))
        self.displayRanges.setText(_translate("MainWindow", "Ants seeing ranges"))
        self.disableGraphics.setText(_translate("MainWindow", "Disable graphics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PreviewTab), _translate("MainWindow", "Simulation Preview"))
        self.stats_label.setText(_translate("MainWindow", "There will be for example statistics, graphs etc."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.StatsTab), _translate("MainWindow", "Stats"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

