# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'worldgen.ui'
#
# Created: Fri May 20 00:39:24 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WorldGenDialog(object):
    def setupUi(self, WorldGenDialog):
        WorldGenDialog.setObjectName("WorldGenDialog")
        WorldGenDialog.setWindowModality(QtCore.Qt.WindowModal)
        WorldGenDialog.resize(382, 396)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WorldGenDialog.sizePolicy().hasHeightForWidth())
        WorldGenDialog.setSizePolicy(sizePolicy)
        WorldGenDialog.setMinimumSize(QtCore.QSize(0, 0))
        WorldGenDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(WorldGenDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(WorldGenDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.line = QtWidgets.QFrame(WorldGenDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(WorldGenDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.worldWidth = QtWidgets.QSpinBox(WorldGenDialog)
        self.worldWidth.setMaximum(1000)
        self.worldWidth.setProperty("value", 200)
        self.worldWidth.setObjectName("worldWidth")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.worldWidth)
        self.label_2 = QtWidgets.QLabel(WorldGenDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.worldHeight = QtWidgets.QSpinBox(WorldGenDialog)
        self.worldHeight.setMaximum(1000)
        self.worldHeight.setProperty("value", 200)
        self.worldHeight.setObjectName("worldHeight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.worldHeight)
        self.label_3 = QtWidgets.QLabel(WorldGenDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.numAnts = QtWidgets.QSpinBox(WorldGenDialog)
        self.numAnts.setMaximum(100000)
        self.numAnts.setProperty("value", 1000)
        self.numAnts.setObjectName("numAnts")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.numAnts)
        self.label_15 = QtWidgets.QLabel(WorldGenDialog)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_4 = QtWidgets.QLabel(WorldGenDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(WorldGenDialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.obstacleFreq = QtWidgets.QSlider(WorldGenDialog)
        self.obstacleFreq.setProperty("value", 50)
        self.obstacleFreq.setOrientation(QtCore.Qt.Horizontal)
        self.obstacleFreq.setObjectName("obstacleFreq")
        self.horizontalLayout_2.addWidget(self.obstacleFreq)
        self.label_9 = QtWidgets.QLabel(WorldGenDialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(WorldGenDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(WorldGenDialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.foodGenerosity = QtWidgets.QSlider(WorldGenDialog)
        self.foodGenerosity.setSliderPosition(25)
        self.foodGenerosity.setOrientation(QtCore.Qt.Horizontal)
        self.foodGenerosity.setObjectName("foodGenerosity")
        self.horizontalLayout_3.addWidget(self.foodGenerosity)
        self.label_10 = QtWidgets.QLabel(WorldGenDialog)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(WorldGenDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(WorldGenDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11, QtCore.Qt.AlignHCenter)
        self.toFoodCoef = QtWidgets.QDial(WorldGenDialog)
        self.toFoodCoef.setMaximumSize(QtCore.QSize(50, 50))
        self.toFoodCoef.setProperty("value", 20)
        self.toFoodCoef.setObjectName("toFoodCoef")
        self.verticalLayout_3.addWidget(self.toFoodCoef, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(WorldGenDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12, QtCore.Qt.AlignHCenter)
        self.fromFoodCoef = QtWidgets.QDial(WorldGenDialog)
        self.fromFoodCoef.setMaximumSize(QtCore.QSize(50, 50))
        self.fromFoodCoef.setProperty("value", 30)
        self.fromFoodCoef.setObjectName("fromFoodCoef")
        self.verticalLayout_5.addWidget(self.fromFoodCoef, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_13 = QtWidgets.QLabel(WorldGenDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13, QtCore.Qt.AlignHCenter)
        self.anthillCoef = QtWidgets.QDial(WorldGenDialog)
        self.anthillCoef.setMaximumSize(QtCore.QSize(50, 50))
        self.anthillCoef.setProperty("value", 50)
        self.anthillCoef.setObjectName("anthillCoef")
        self.verticalLayout_4.addWidget(self.anthillCoef, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_16 = QtWidgets.QLabel(WorldGenDialog)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.percentScouts = QtWidgets.QSlider(WorldGenDialog)
        self.percentScouts.setMaximum(100)
        self.percentScouts.setProperty("value", 10)
        self.percentScouts.setOrientation(QtCore.Qt.Horizontal)
        self.percentScouts.setObjectName("percentScouts")
        self.horizontalLayout_5.addWidget(self.percentScouts)
        self.label_17 = QtWidgets.QLabel(WorldGenDialog)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(WorldGenDialog)
        self.buttonBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMaximumSize(QtCore.QSize(176, 16777215))
        self.buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.actionExit = QtWidgets.QAction(WorldGenDialog)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(WorldGenDialog)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(WorldGenDialog)
        self.buttonBox.accepted.connect(WorldGenDialog.accept)
        self.buttonBox.rejected.connect(WorldGenDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(WorldGenDialog)

    def retranslateUi(self, WorldGenDialog):
        _translate = QtCore.QCoreApplication.translate
        self.label_14.setText(_translate("WorldGenDialog", "Tweak world params"))
        self.label.setText(_translate("WorldGenDialog", "World width"))
        self.label_2.setText(_translate("WorldGenDialog", "World height"))
        self.label_3.setText(_translate("WorldGenDialog", "Number of ants"))
        self.label_15.setText(_translate("WorldGenDialog", "Ratio of scouts"))
        self.label_4.setText(_translate("WorldGenDialog", "Obstacle frequency"))
        self.label_7.setText(_translate("WorldGenDialog", "Few"))
        self.label_9.setText(_translate("WorldGenDialog", "Lots"))
        self.label_5.setText(_translate("WorldGenDialog", "Foods generosity"))
        self.label_8.setText(_translate("WorldGenDialog", "Few"))
        self.label_10.setText(_translate("WorldGenDialog", "Lots"))
        self.label_6.setText(_translate("WorldGenDialog", "Pheromone decay rates"))
        self.label_11.setText(_translate("WorldGenDialog", "To food"))
        self.label_12.setText(_translate("WorldGenDialog", "From food"))
        self.label_13.setText(_translate("WorldGenDialog", "Anthill"))
        self.label_16.setText(_translate("WorldGenDialog", "0%"))
        self.label_17.setText(_translate("WorldGenDialog", "100%"))
        self.actionExit.setText(_translate("WorldGenDialog", "Exit"))
        self.actionAbout.setText(_translate("WorldGenDialog", "About"))

